"""
Pairwise ML Matching module using LightGBM.
Trains a classical supervised pairwise classifier on positive matches and hard negatives
generated by blocking, followed by threshold calibration optimizing macro F0.5 with singletons.
"""

from pathlib import Path
from typing import Dict, List, Set, Tuple, Any, Optional

import lightgbm as lgb
import numpy as np

try:
    from src.config import LGBM_PARAMS
    from src.features import FEATURE_NAMES
except ImportError:
    from .config import LGBM_PARAMS
    from .features import FEATURE_NAMES




class PairwiseClassifier:
    """Supervised LightGBM classifier for pairwise entity matching."""

    def __init__(self, params: Optional[Dict[str, Any]] = None):
        self.params = params or LGBM_PARAMS
        self.model = lgb.LGBMClassifier(**self.params)
        self.feature_names = FEATURE_NAMES
        self.threshold = 0.50

    def fit(self, X: np.ndarray, y: np.ndarray) -> "PairwiseClassifier":
        """Train the classifier on extracted pairwise features."""
        print(f"Training LightGBM on {len(X):,} pairs (Positives: {int(np.sum(y)):,}, Negatives: {int(len(y) - np.sum(y)):,})...")
        self.model.fit(X, y)
        print("Model training complete.")
        return self

    def predict_proba(self, X: np.ndarray) -> np.ndarray:
        """Return match probability for pairwise features."""
        if len(X) == 0:
            return np.array([])
        return self.model.predict_proba(X)[:, 1]

    def save(self, path: Path) -> None:
        """Save model booster to disk."""
        path.parent.mkdir(parents=True, exist_ok=True)
        self.model.booster_.save_model(str(path))
        print(f"Saved model artifact to: {path}")

    def load(self, path: Path) -> "PairwiseClassifier":
        """Load trained booster from disk."""
        booster = lgb.Booster(model_file=str(path))
        self.model = lgb.LGBMClassifier(**self.params)
        self.model._Booster = booster
        self.model.fitted_ = True
        print(f"Loaded model artifact from: {path}")
        return self


def calculate_f05_score(precision: float, recall: float) -> float:
    """
    Compute F_0.5 score:
    F0.5 = (1.25 * Precision * Recall) / (0.25 * Precision + Recall)
    """
    denom = 0.25 * precision + recall
    if denom == 0:
        return 0.0
    return (1.25 * precision * recall) / denom


def evaluate_macro_f05_at_threshold(
    val_s1_ids: List[str],
    val_gt: Dict[str, Set[str]],
    val_predictions: Dict[str, List[Tuple[str, float]]],
    threshold: float
) -> Tuple[float, float, float, float]:
    """
    Compute macro-averaged F0.5 across all validation Source 1 entities including singletons.
    Returns (macro_f05, macro_precision, macro_recall, singleton_accuracy).
    """
    total_f05 = 0.0
    total_prec = 0.0
    total_rec = 0.0
    singleton_correct = 0
    total_singletons = 0

    for s1_id in val_s1_ids:
        gt_ids = val_gt.get(s1_id, set())
        cands_with_prob = val_predictions.get(s1_id, [])
        pred_ids = {cid for cid, p in cands_with_prob if p >= threshold}

        is_singleton = (len(gt_ids) == 0)
        if is_singleton:
            total_singletons += 1
            if len(pred_ids) == 0:
                singleton_correct += 1
                total_f05 += 1.0
                total_prec += 1.0
                total_rec += 1.0
            else:
                total_f05 += 0.0
                total_prec += 0.0
                total_rec += 0.0
        else:
            if len(pred_ids) == 0:
                total_f05 += 0.0
                total_prec += 0.0
                total_rec += 0.0
            else:
                tp = len(gt_ids & pred_ids)
                prec = tp / len(pred_ids)
                rec = tp / len(gt_ids)
                f05 = calculate_f05_score(prec, rec)
                total_f05 += f05
                total_prec += prec
                total_rec += rec

    n = len(val_s1_ids)
    macro_f05 = total_f05 / n if n > 0 else 0.0
    macro_prec = total_prec / n if n > 0 else 0.0
    macro_rec = total_rec / n if n > 0 else 0.0
    singleton_acc = singleton_correct / total_singletons if total_singletons > 0 else 1.0

    return macro_f05, macro_prec, macro_rec, singleton_acc


def calibrate_threshold(
    val_s1_ids: List[str],
    val_gt: Dict[str, Set[str]],
    val_predictions: Dict[str, List[Tuple[str, float]]],
    min_tau: float = 0.20,
    max_tau: float = 0.85,
    step: float = 0.02
) -> Tuple[float, float, Dict[str, float]]:
    """
    Sweep classification threshold over [min_tau, max_tau] to find threshold maximizing macro F0.5.
    Returns (best_threshold, best_f05, best_metrics_dict).
    """
    best_tau = 0.50
    best_f05 = -1.0
    best_metrics = {}

    thresholds = np.arange(min_tau, max_tau + step, step)
    for tau in thresholds:
        tau = round(float(tau), 3)
        f05, prec, rec, s_acc = evaluate_macro_f05_at_threshold(
            val_s1_ids, val_gt, val_predictions, tau
        )
        if f05 > best_f05:
            best_f05 = f05
            best_tau = tau
            best_metrics = {
                "threshold": tau,
                "macro_f05": f05,
                "macro_precision": prec,
                "macro_recall": rec,
                "singleton_accuracy": s_acc
            }

    print(f"Threshold calibration: Optimal threshold = {best_tau:.3f} achieving Macro F0.5 = {best_f05:.4f} "
          f"(Precision = {best_metrics['macro_precision']:.4f}, Recall = {best_metrics['macro_recall']:.4f}, "
          f"Singleton Acc = {best_metrics['singleton_accuracy']:.4f})")

    return best_tau, best_f05, best_metrics
